### ISSUE TITLE
Nuxt DevTools error

### ISSUE THREAD

**Issue by frasza** [nuxt/fonts#52] opened 2024-03-11 10:10 UTC
Hey 👋

Recently I have set up new Nuxt project with fonts module and based on v 0.2 I am receiving regular errors in console:

```bash
 ERROR  [unhandledRejection] [birpc] timeout on calling "nuxt-devtools-fonts:exposeFonts"  11:08:21  

  at Timeout._onTimeout (/C:/Users/zanfr/Work/Code/SmartCity/web-next/node_modules/birpc/dist/index.mjs:42:23)
  at listOnTimeout (node:internal/timers:573:17)
  at process.processTimers (node:internal/timers:514:7)
```

The errors seems to be displayed on regular interval on it own after dev server is running for some time. Can't really say.
If needed I will try to give reproduction, altho, its fresh Nuxt project.

**Comment by danielroe** [comment] 2024-03-11 15:39
I can't reproduce (I suspect it's a Windows issue with devtools) but I've pushed a _possible_ fix in 0.2.1. Let me know if it resolves it for you.

I note that @harlan-zw ignores errors and wonder if he encountered something similar:

https://github.com/nuxt-modules/og-image/blob/be96e004c73ee88e8305053c41bcfa3f53c60d60/src/build/devtools.ts#L52-L53

**Comment by harlan-zw** [comment] 2024-03-12 00:23
As far as I understand it, when sending rpc messages on Nuxt events, there may be no client connected which ends up throwing an error. To avoid this I just ignore the errors, not ideal but couldn't find a solution.

**Comment by danielroe** [comment] 2024-03-12 23:30
I'm closing this as I think we've resolved with `asEvent`. Let me know if it reoccurs for you...

**Closed by danielroe** 2024-03-12 23:30 UTC
Labels: bug
