### ISSUE TITLE
Bug when importing `defineFontProvider`: Package subpath './utils' is not defined by "exports"

### ISSUE THREAD

**Issue by ziadomalik** [nuxt/fonts#170] opened 2024-06-01 23:31 UTC
#### Output of `npx nuxi info`:

```
Nuxt project info: 

------------------------------
- Operating System: Linux
- Node Version:     v20.14.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.1.4
- Builder:          -
- User Config:      devtools, modules, fonts
- Runtime Modules:  @nuxt/fonts@0.7.0
- Build Modules:    -
------------------------------
```

#### My custom provider in `~/providers/ComputerModernFontProvider.ts`:

```ts
import { defineFontProvider } from '@nuxt/fonts/utils'

export default defineFontProvider({
  async resolveFontFaces (fontFamily, defaults) {
    if (fontFamily === 'Computer Modern') {
      return { 
        fonts: [
          { 
            weight: 400,
            style: 'normal',
            src: { url: '<link-to-cdn>', format: 'otf' },
          },
          { 
            weight: 400,
            style: 'italic',
            src: { url: '<link-to-cdn>', format: 'otf' },
          },
          { 
            weight: 700,
            style: 'normal',
            src: { url: '<link-to-cdn>', format: 'otf' },
          },
        ]
      }
    }
  }
})
```

#### Picture of the Error:

![image](https://github.com/nuxt/fonts/assets/135853660/b1b0f63f-ff19-4b18-94e2-578e07737521)

#### Steps & Contribution

I find this super weird since `./utils` **is** already defined in the `package.json` [here](https://github.com/nuxt/fonts/blob/8a00c3b0771bbcf0cd34c9e2a854eb77b501d8ff/package.json#L17).
If someone could give me some pointers towards the solution, I'd happily create a PR.
Thank you in advance.

**Comment by danielroe** [comment] 2024-06-02 19:49
Possibly the issue is that we don't provide a solution for CJS/require, which might be how jiti is resolving the import. We can amend the build config.

**Closed** 2024-09-23 12:06 UTC
