### ISSUE TITLE
Font is not loading

### ISSUE THREAD

**Issue by maxdzin** [nuxt/fonts#75] opened 2024-03-19 22:37 UTC
Hello guys!

I followed the documentation and tried a couple of settings/scenarios, but cannot make it work in some of my Nuxt projects - the font is not loaded.
There's used tailwindcss, so the font family is specified there;
```ts
export default {
  ...
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', ...defaultTheme.fontFamily.sans],
      },
      ...
    },
  },
}
```
but the font is not loaded and just used system default.

I also tried to specify it within my `main.scss` file (that is specified in `nuxt.config.ts`, of course):
```scss
...
body {
  font-family: Inter, sans-serif;
}
```
But that doesn't help.
As well as trying some fine-grained settings in the Nuxt config file:
```ts
export default defineNuxtConfig({
  ...
  fonts: {
    families: [{ name: 'Inter', provider: 'google' }],
    defaults: {
      weights: [400, 500, 600, 700],
      styles: ['normal', 'italic'],
      subsets: ['latin-ext', 'latin'],
    },
  },
  ...
})
```

as well as this:
```ts
export default defineNuxtConfig({
  ...
  fonts: {
    families: [
      {
        name: 'Inter',
        provider: 'google',
        weights: [400, 500, 600, 700],
        styles: ['normal', 'italic'],
        subsets: ['latin-ext', 'latin'],
      },
    ],
  },
  ...
})
```

I see there are a few other issues that mention some problems with the variable font (and I'm trying to use `Inter` which is variable), so I'm not sure if it's related to some variable font support issue (if any) or there is something else.
I would be grateful if you could point this out to me.

**Comment by maxdzin** [comment] 2024-03-20 16:20
@danielroe sure. I'll share ASAP.

**Comment by robokozo** [comment] 2024-03-23 04:10
@maxdzin is it working with `nuxt dev` during local development?

I reported an issue recently with fonts on twitter and I promised to come up with a reproduction. (@danielroe)
Really nothing fancy at all: https://stackblitz.com/edit/github-29x8jz

`nuxt build`
`nuxt preview`

_Please note: `nuxt dev` has the correct font loading_

Originally I reported on twitter as potentially an issue with AWS amplify hosting (which you can see deployed [here](https://main.dbkaf0wl3amae.amplifyapp.com/)) but as seen in the stack blitz, it isn't loading there on build either.

The font in question is: https://fonts.google.com/specimen/Press+Start+2P
as recommended by https://nostalgic-css.github.io/NES.css/

**Comment by danielroe** [comment] 2024-03-23 11:59
@robokozo Published a fix for your situation. Thanks for the reproduction.

@maxdzin I can't reproduce the issue with Inter. If you're able to provide a reproduction, I can likely resolve 🙏

**Comment by maxdzin** [comment] 2024-03-24 01:30
@danielroe Thank you, Daniel!

I created a reproduction: https://github.com/maxdzin/nuxt-fonts-test

The problem is that the fonts are not loaded even though they are specified in `nuxt.config.ts` and `tailwind.config.ts`.
And there's an error dropped from the start:
```
ERROR  Could not fetch metadata for Inter from google. fetch failed
```
and then this warning right after it:
```
WARN  Could not produce font face declaration from google for font family Inter.
```

Apart from that issue, I also trying to achieve dynamic font style switching.
Please, look at `fonts` page in the reproduction repo, and let me know if that is possible to achieve with nuxt/fonts module.
I tried to apply the font by styles - font family and weight, but that's not working.

Environment details:
------------------------------
- Operating System: Linux
- Node Version:     v20.11.1
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.4
- Package Manager:  pnpm@8.15.5
- Builder:          -
- User Config:      devtools, modules, fonts
- Runtime Modules:  @nuxt/fonts@0.5.1, @nuxtjs/tailwindcss@6.11.4
- Build Modules:    -
------------------------------

**Comment by maxdzin** [comment] 2024-03-24 01:33
@robokozo No, it doesn't work. Neither for dev or build.

**Comment by robokozo** [comment] 2024-03-24 02:14
@maxdzin Hey Max - I tried creating a minimal repo with the font you're trying to use + tailwind but it was working correctly for me. https://stackblitz.com/edit/github-qda5kf

**Comment by maxdzin** [comment] 2024-03-24 14:24
@robokozo thank you, that seems helps to understand the problem better.

Today I tried to investigate again and here's what I found:
the font family "Inter" is loaded, which is great, but the problem appears with its regular weight - it is shown as a black (900) font instead of regular (400).

And that setup seems related to the environment:
@robokozo in Stackblitz you shared there's used **node v18** and **npm** as a package manager.

I tried to use Codesandbox, where **node v20.9.0** and **pnpm** package manager is used. And there is where we can reproduce that issue.
@danielroe take a look. please, at this reproduction:
https://codesandbox.io/p/devbox/youthful-butterfly-36fxdj

**Comment by danielroe** [comment] 2024-04-17 16:30
This seems to be working fine for me with node v20.12.2 and pnpm. I suspect it's a caching issue or was fixed subsequently to your reproduction.

I'm going to close this but if you can reproduce again, please do let me know and I'll reopen. 🙏

**Closed by danielroe** 2024-04-17 16:30 UTC

**Comment by maxdzin** [comment] 2024-04-17 18:49
@danielroe Thank you 🙏
So, as mentioned above, after changing the tailwind configuration, it started working fine.
